#!/usr/bin/env zsh
#
# This loads the plugins by sourcing a file.
# To generate the file the plugin definitions are loaded from ~/.zsh-plugins.
# If the ~/.zsh-plugins file is newer then the definition file is regenerated.

readonly PLUGIN_FOLDER="${0:A:h}"

readonly PLUGIN_FILE="${HOME}/.zsh-plugins"
readonly CACHE_FOLDER="${XDG_CACHE_DIR:-${HOME}/.cache}/dotfiles"
readonly LOG_FOLDER="${CACHE_FOLDER}/logs"
readonly LOG_FILE="${LOG_FOLDER}/install"
readonly COMPILED_FILE="${CACHE_FOLDER}/commands.zsh"

if [ ! -e "${CACHE_FOLDER}" ]; then
    mkdir -p "${CACHE_FOLDER}"
fi
if [ ! -e "${LOG_FOLDER}" ]; then
    mkdir -p "${LOG_FOLDER}"
fi
COMMAND_PREFIX=install PATH="${PLUGIN_FOLDER}:${PATH}" "${PLUGIN_FILE}" >${LOG_FILE}.log

if [ "${_CLEAR_ERREXIT}" = "1" ]; then
    unsetopt errexit
    unset _CLEAR_ERREXIT
fi
if [ "${_CLEAR_NOUNSET}" = "1" ]; then
    unsetopt nounset
    unset _CLEAR_NOUNSET
fi
if [ "${_CLEAR_PIPEFAIL}" = "1" ]; then
    unsetopt pipefail
    unset _CLEAR_PIPEFAIL
fi
