#!/usr/bin/zsh
#
# This loads a dependency from a github release.
# This will download the file to the xdg cache.
#
# This takes the most recent release that matches the patterns, downloads and decompresses it.
# Then it will put the root folder on the path, and add any autocomplete folder to autocomplete.
#
# This uses tags to identify which release to use.
# The terms: tag takes a comma separated list of words to look for in the filename of the release.
#
# Example:
#
# @load github-release sharkdp/fd terms:x86_64,linux,musl
#
# The commands to execute will be echoed to stdout.

set -euo pipefail

readonly PLUGIN_FOLDER="${0:A:h}"

readonly RELEASE_CACHE_FOLDER="${XDG_CACHE_DIR:-${HOME}/.cache}/dotfiles/repos/releases"

readonly REPO_NAME="${1?You must provide the repo to use}"
readonly FOLDER_NAME="${RELEASE_CACHE_FOLDER}/${REPO_NAME:s#/#--#}"
shift

if [ ! -e "${FOLDER_NAME}" ]; then
    if [ ! -e "${RELEASE_CACHE_FOLDER}" ]; then
        mkdir -p "${RELEASE_CACHE_FOLDER}"
    fi

    readonly TEMP_DIR="$(mktemp -d)"
    trap "rm -rf '${TEMP_DIR}'" HUP INT QUIT

    TERMS=""
    for argument in "$@"; do
        case $argument in
            terms:*)
                TERMS="${argument/*:}"
                ;;
            *)
                echo "Unknown argument: ${argument}" >&2
                exit 1
                ;;
        esac
    done

    readonly RELEASE_URL="$(curl https://api.github.com/repos/sharkdp/fd/releases/latest | python ${PLUGIN_FOLDER}/github_release.py "${TERMS}")"
    (
        cd "${TEMP_DIR}"
        wget "${RELEASE_URL}"
        tar xzf *.tar.gz
        rm *.tar.gz
        mv * "${FOLDER_NAME}"
    )
fi

"${PLUGIN_FOLDER}/@load" directory "${FOLDER_NAME}"
