#!/usr/bin/zsh
#
# This loads the plugins by sourcing a file.
# To generate the file the plugin definitions are loaded from ~/.zsh-plugins.
# If the ~/.zsh-plugins file is newer then the definition file is regenerated.

if [ ! -o errexit ]; then
    setopt errexit
    _CLEAR_ERREXIT=1
fi
if [ ! -o nounset ]; then
    setopt nounset
    _CLEAR_NOUNSET=1
fi
if [ ! -o pipefail ]; then
    setopt pipefail
    _CLEAR_PIPEFAIL=1
fi

readonly PLUGIN_FOLDER="${0:A:h}"

readonly PLUGIN_FILE="${HOME}/.zsh-plugins"
readonly CACHE_FOLDER="${XDG_CACHE_DIR:-${HOME}/.cache}/dotfiles"
readonly COMPILED_FILE="${CACHE_FOLDER}/commands.zsh"

if [ ! -e "${COMPILED_FILE}" ] || [ "${PLUGIN_FILE:A}" -nt "${COMPILED_FILE}" ]; then
    if [ ! -e "${CACHE_FOLDER}" ]; then
        mkdir -p "${CACHE_FOLDER}"
    fi

    COMMAND_PREFIX=load PATH="${PLUGIN_FOLDER}:${PATH}" "${PLUGIN_FILE}" > "${COMPILED_FILE}"

    (
        autoload -U zrecompile
        local file
        for file in $CACHE_FOLDER/**/*.zsh{,-theme}(N); do
            zrecompile -pq "${file}"
        done
    )
fi
source "${COMPILED_FILE}"

if [ "${_CLEAR_ERREXIT}" = "1" ]; then
    unsetopt errexit
    unset _CLEAR_ERREXIT
fi
if [ "${_CLEAR_NOUNSET}" = "1" ]; then
    unsetopt nounset
    unset _CLEAR_NOUNSET
fi
if [ "${_CLEAR_PIPEFAIL}" = "1" ]; then
    unsetopt pipefail
    unset _CLEAR_PIPEFAIL
fi
