#!/usr/bin/zsh
#
# This loads a dependency from a github release.
# This will download the file to the xdg cache.
#
# This takes the most recent release that matches the patterns, downloads and decompresses it.
# Then it will put the root folder on the path, add any autocomplete folder to autocomplete.
#
# The commands to execute will be echoed to stdout.

set -euo pipefail

readonly PLUGIN_FOLDER="${0:A:h}"

readonly CLONE_CACHE_FOLDER="${XDG_CACHE_DIR:-${HOME}/.cache}/dotfiles/repos/clones"

readonly URL="${1?You must provide the https url to use}"
readonly FOLDER_NAME="${CLONE_CACHE_FOLDER}/${URL:gs#/#--#:gs#:##}"
shift

if [ ! -e "${FOLDER_NAME}" ]; then
    if [ ! -e "${CLONE_CACHE_FOLDER}" ]; then
        mkdir -p "${CLONE_CACHE_FOLDER}"
    fi

    git clone "${URL}" "${FOLDER_NAME}"
fi

"${PLUGIN_FOLDER}/@load" directory "${FOLDER_NAME}"
