#!/usr/bin/zsh
#
# This is the entrypoint for the plugin manager initialization.
# This takes a subcommand as the following terms, and then invokes it.
# It is that command which generates the output.
#
# This leads to a command which is like:
#
# @load dotfile python
#
# Which would invoke
#
# load/@dotfile python
#
# The commands to execute will be echoed to stdout.

set -euo pipefail

readonly PLUGIN_FOLDER="${0:A:h}"
readonly COMMAND="${1?provide the command to invoke}"
shift

if [ "${COMMAND}" = "if" ]; then
    FILE="${PLUGIN_FOLDER}/@if"
else
    FILE="${PLUGIN_FOLDER}/load/@${COMMAND}"
fi

COMMAND_PREFIX=load "${FILE}" "$@"
