#!/usr/bin/zsh
#
# This will execute the install.sh script of the dotfile directory if it is present.

set -euo pipefail

readonly PLUGIN_FOLDER="${0:A:h:h}"
readonly DOTFILES_FOLDER="${0:A:h:h:h}"

source "${PLUGIN_FOLDER}/lib.sh"
source "${DOTFILES_FOLDER}/script/lib.sh"

readonly FOLDER="${DOTFILE_FOLDER}/${1?provide the folder to use}"
readonly LOG_FILE="$(log_file "${FOLDER}")"

if [ -e "${FOLDER}/install.sh" ]; then
    "${FOLDER}/install.sh" >"${LOG_FILE}.log" 2>"${LOG_FILE}.err"
fi
