#!/usr/bin/zsh
#
# This is a conditional executor which takes a few keywords.
# The subsequent command will only be executed if every keyword test passes.
# The format is as follows:
#
# @load if ssh x86_64 then directory python
# @load if ! ssh x86_64 then directory python
# @load if not ssh x86_64 then directory python
#
# This will only run the @load-directory python if accessed over ssh and on a linux machine.
# These are the available tests:
#
#  * ssh - is the current connection remote (over ssh)
#  * linux - is the `uname --machine` x86_64
#  * termux - is the `uname --machine` aarch64
#
# Since the machine architecture is static that is tested once and discarded.
# The ssh connection involves wrapping the commands that would be executed.
#
# The commands to execute will be echoed to stdout.

set -euo pipefail

readonly PLUGIN_FOLDER="${0:A:h}"

if [ "${1}" = "!" ] || [ "${1}" = "not" ]; then
    shift
    is_not_ssh() {
        [ ! -v SSH_CONNECTION ]
    }
    is_not_uname() {
        [ "$(uname --machine)" = "${1}" ]
    }
else
    is_not_ssh() {
        [ -v SSH_CONNECTION ]
    }
    is_not_uname() {
        [ "$(uname --machine)" != "${1}" ]
    }
fi

for command in "$@"; do
    shift
    case $command in
        ssh)
            if is_not_ssh; then
                exit
            fi
            ;;
        linux)
            if is_not_uname "x86_64"; then
                exit
            fi
            ;;
        android)
            if is_not_uname "aarch64"; then
                exit
            fi
            ;;
        then)
            break
            ;;
        *)
            echo "Unknown term: ${command}" >&2
            exit 1
            ;;
    esac
done

readonly COMMAND="${1?provide the command to invoke}"
shift

"${PLUGIN_FOLDER}/@${COMMAND}" "$@"
